# Generated by Django 5.2 on 2026-07-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_order_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedmessageattempt',
            name='reason',
            field=models.CharField(choices=[('contact_info', 'Contact Info Sharing'), ('off_platform', 'Off-Platform Payment Solicitation'), ('unpaid', 'Chat Not Yet Unlocked'), ('expired', 'Chat Expired (Order Completed)')], max_length=20),
        ),
    ]
