# Generated by Django 5.2 on 2026-05-10 15:46

import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellerapplication_admission_letter_alter_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='nin_document',
            field=models.FileField(blank=True, help_text='NIN slip or NIN card (JPG, PNG, or PDF)', null=True, upload_to='seller_verification/nin/', validators=[studex.validators.validate_id_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_back',
            field=models.FileField(blank=True, help_text='Back of student ID card (JPG, PNG, or PDF)', null=True, upload_to='seller_verification/id_back/', validators=[studex.validators.validate_id_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_front',
            field=models.FileField(blank=True, help_text='Front of student ID card (JPG, PNG, or PDF)', null=True, upload_to='seller_verification/id_front/', validators=[studex.validators.validate_id_document]),
        ),
    ]
