# Generated by Django 5.2 on 2026-05-19 16:42

import accounts.models
import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='admission_letter',
            field=models.FileField(blank=True, help_text='Admission letter or proof of enrollment (PDF, JPG, PNG)', null=True, storage=accounts.models._raw_storage, upload_to='seller_verification/admission/', validators=[studex.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_back',
            field=models.FileField(blank=True, help_text='Back of student ID card (JPG, PNG, or PDF)', null=True, storage=accounts.models._raw_storage, upload_to='seller_verification/id_back/', validators=[studex.validators.validate_id_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_front',
            field=models.FileField(blank=True, help_text='Front of student ID card (JPG, PNG, or PDF)', null=True, storage=accounts.models._raw_storage, upload_to='seller_verification/id_front/', validators=[studex.validators.validate_id_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='nin_document',
            field=models.FileField(blank=True, help_text='NIN slip or NIN card (JPG, PNG, or PDF)', null=True, storage=accounts.models._raw_storage, upload_to='seller_verification/nin/', validators=[studex.validators.validate_id_document]),
        ),
    ]
