# Generated by Django 5.2 on 2026-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_personal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('vendor', 'Vendor'), ('rider', 'Rider')], default='student', max_length=10),
        ),
    ]
