# Generated by Django 5.2 on 2026-07-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('settlement_trigger', models.CharField(choices=[('buyer_confirmation', 'Buyer Confirmation / Auto-Release'), ('pickup_verification', 'Rider Pickup Verification')], default='buyer_confirmation', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Type',
                'verbose_name_plural': 'Vendor Types',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounts.vendortype'),
        ),
    ]
