# Generated by Django 5.2 on 2026-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_seed_vendor_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortype',
            name='supports_batched_delivery',
            field=models.BooleanField(default=False, help_text='Vendors of this type can use scheduled Delivery Batches with capacity limits.'),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='supports_menu_ordering',
            field=models.BooleanField(default=False, help_text='Vendors of this type can build a menu (categories, items, add-ons) instead of plain listings.'),
        ),
    ]
