# Generated by Django 5.2 on 2026-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_seed_food_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortype',
            name='catalog_item_label',
            field=models.CharField(default='Item', help_text='What a single catalog entry is called, e.g. "Dish" or "Service".', max_length=50),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='catalog_label',
            field=models.CharField(default='Menu', help_text='What the catalog is called for this vendor type, e.g. "Menu" or "Services".', max_length=50),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='catalog_route_slug',
            field=models.SlugField(default='catalog', help_text='URL segment for this type\'s catalog-management page under /vendor/dashboard/, e.g. "kitchen".'),
        ),
    ]
