# Generated by Django 5.2 on 2026-07-30 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_seed_catalog_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='free_delivery_quota',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='First N delivery orders are free. Leave blank to always charge the fee above.', null=True),
        ),
    ]
