# Generated by Django 5.2 on 2026-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_vendor_delivery_fee_vendor_free_delivery_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_paused',
            field=models.BooleanField(default=False, help_text='When on, checkout shows no delivery slots for this vendor at all — existing slots are preserved, not deleted.'),
        ),
    ]
