# Generated by Django 5.2 on 2026-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_paystack_response_paymenttransaction_flw_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='flw_transaction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
