# Generated by Django 5.2 on 2026-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_migrate_flw_fields_to_paystack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='flw_response',
            new_name='paystack_response',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='flw_transaction_id',
            new_name='paystack_transaction_id',
        ),
        migrations.RenameField(
            model_name='sellerbankaccount',
            old_name='flw_subaccount_id',
            new_name='paystack_subaccount_code',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=205.56, max_digits=10),
        ),
    ]
