# Generated by Django 5.2 on 2026-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymenttransaction_transfer_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
