# Generated by Django 5.2 on 2026-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymenttransaction_deal_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='deal_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paystack_charge_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transfer_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
