# Generated by Django 5.2 on 2026-07-21 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_pricingsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('paystack_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_held_for_vendors', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_platform_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discrepancy', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_flagged', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escrow Reconciliation Log',
                'verbose_name_plural': 'Escrow Reconciliation Logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['-checked_at'], name='payments_es_checked_3fbac8_idx'), models.Index(fields=['is_flagged', 'resolved'], name='payments_es_is_flag_c3b120_idx')],
            },
        ),
    ]
