# Generated by Django 5.2 on 2026-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_vendordebt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('refund_pending', 'Refund Pending')], default='pending', max_length=20),
        ),
    ]
