# Generated by Django 5.2 on 2026-07-22 06:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryassignment_code_attempts_and_more'),
        ('payments', '0016_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('pickup_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_evidence_image', models.URLField(blank=True, max_length=500, null=True)),
                ('transfer_reference', models.CharField(blank=True, default='', max_length=200)),
                ('transfer_status', models.CharField(blank=True, default='', max_length=50)),
                ('amount_released', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_audits', to='delivery.deliveryassignment')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_audits_as_rider', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_audit', to='payments.paymenttransaction')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Audit Record',
                'verbose_name_plural': 'Payout Audit Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor'], name='payments_pa_vendor__60e924_idx'), models.Index(fields=['rider'], name='payments_pa_rider_i_0514a9_idx')],
            },
        ),
    ]
