# Generated by Django 5.2 on 2026-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_payoutauditrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('imsu', 'IMSU')], max_length=20, unique=True)),
                ('service_fee_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit the global platform fee.', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus Pricing Override',
                'verbose_name_plural': 'Campus Pricing Overrides',
                'ordering': ['campus'],
            },
        ),
    ]
