# Generated by Django 5.2 on 2026-07-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_seed_vendor_types'),
        ('payments', '0018_campuspricingsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuspricingsettings',
            options={'ordering': ['campus', 'vendor_type'], 'verbose_name': 'Campus Pricing Override', 'verbose_name_plural': 'Campus Pricing Overrides'},
        ),
        migrations.AddField(
            model_name='campuspricingsettings',
            name='vendor_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a campus-wide default (Level 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_pricing_overrides', to='accounts.vendortype'),
        ),
        migrations.AlterField(
            model_name='campuspricingsettings',
            name='campus',
            field=models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('imsu', 'IMSU')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campuspricingsettings',
            name='service_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit the next level up.', max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='campuspricingsettings',
            unique_together={('campus', 'vendor_type')},
        ),
    ]
