# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
        ('payments', '0020_banktransfersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_bank_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ManualRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[
                    ('awaiting_bank_details', "Awaiting Buyer's Bank Details"),
                    ('awaiting_admin_action', 'Awaiting Admin Payout'),
                    ('completed', 'Refunded'),
                ], default='awaiting_bank_details', max_length=30)),
                ('buyer_account_name', models.CharField(blank=True, max_length=150)),
                ('buyer_account_number', models.CharField(blank=True, max_length=20)),
                ('buyer_bank_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_refunds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_refunds', to='orders.orderitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_refunds_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Refund',
                'verbose_name_plural': 'Manual Refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
