# Generated by Django 5.2
"""
Data migration: backfill is_bank_transfer=True for every PaymentTransaction
already created via the bank-transfer checkout path (payments.views.
initiate_bank_transfer_cart) before the is_bank_transfer field existed —
migration 0021 added the field with default=False, which silently mislabeled
every pre-existing bank-transfer transaction as a normal Paystack one. That
caused payments.item_refund.mark_order_item_unavailable to keep calling
refund_paystack_transaction for those orders, which always failed since
Paystack never saw that reference.

Reference prefix 'STX-BANKXFER-' is unique to initiate_bank_transfer_cart
(see payments/views.py) — a safe, deterministic backfill criterion.
"""
from django.db import migrations


def backfill_is_bank_transfer(apps, schema_editor):
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    PaymentTransaction.objects.filter(reference__startswith='STX-BANKXFER-').update(is_bank_transfer=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_manualrefund_and_is_bank_transfer'),
    ]

    operations = [
        migrations.RunPython(backfill_is_bank_transfer, noop_reverse),
    ]
