# Generated by Django 5.2 on 2026-07-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_reserved_at'),
        ('services', '0028_addongroup_addon_menucategory_menuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta_at_add_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_selections', to='services.addon')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='cart.cartitem')),
            ],
            options={
                'verbose_name': 'Cart Item Add-on',
                'verbose_name_plural': 'Cart Item Add-ons',
            },
        ),
    ]
