# Generated by Django 5.2 on 2026-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemaddon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
