# Generated by Django 5.2 on 2026-07-12 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_booking_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('seller_completed', 'Seller Marked Complete'), ('completed', 'Buyer Confirmed - Complete'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('vendor_declined', 'Vendor Declined')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='BookingReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='orders.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
