# Generated by Django 5.2 on 2026-07-13 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_booking_quantity_order_quantity'),
        ('services', '0025_listingvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.listingvariant'),
        ),
    ]
