# Generated by Django 5.2 on 2026-07-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_batchtemplate_deliverybatch_deliveryassignment_batch'),
        ('orders', '0014_orderitem_orderitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_orders', to='delivery.deliverybatch'),
        ),
    ]
