# Generated by Django 5.2 on 2026-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delivery_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemaddon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
