# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_delivery_fee_order_delivery_fee_waived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Payment'),
                    ('pending_bank_transfer', 'Awaiting Bank Transfer Confirmation'),
                    ('paid', 'Paid'),
                    ('seller_completed', 'Seller Marked Complete'),
                    ('completed', 'Buyer Confirmed - Complete'),
                    ('disputed', 'Disputed'),
                    ('cancelled', 'Cancelled'),
                    ('vendor_declined', 'Vendor Declined'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
    ]
