# Generated by Django 5.2
"""
Data migration: cancel every Order whose items are ALL 'unavailable' but
whose own status was never updated to reflect that.

payments.item_refund.mark_order_item_unavailable only started setting
Order.status = 'cancelled' once every item on an order becomes unavailable
as of the commit that added this migration — any order where a rider
marked the last (or only) item unavailable before that fix existed was
left stuck reading "in progress" to the buyer forever, even with nothing
left to fulfill. This is a one-time correction for orders already in that
state; the application code now keeps new ones from happening.
"""
from django.db import migrations


def backfill_cancelled_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')

    order_ids_with_items = set(OrderItem.objects.values_list('order_id', flat=True).distinct())
    order_ids_with_a_fulfilled_item = set(
        OrderItem.objects.exclude(status='unavailable').values_list('order_id', flat=True).distinct()
    )
    order_ids_fully_unavailable = order_ids_with_items - order_ids_with_a_fulfilled_item

    Order.objects.filter(id__in=order_ids_fully_unavailable).exclude(status='cancelled').update(status='cancelled')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(backfill_cancelled_orders, noop_reverse),
    ]
