# Generated by Django 5.2 on 2026-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_backfill_cancelled_all_items_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer_proof',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
