# Generated by Django 5.2 on 2026-08-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_bank_transfer_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRefundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=72)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_timeout_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_timeout_warned',
            field=models.BooleanField(default=False),
        ),
    ]
