# Generated by Django 5.2 on 2026-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_autorefundsettings_order_vendor_timeout_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorefundsettings',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
