# Generated by Django 5.2 on 2026-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspickuppoint',
            name='campus',
            field=models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('imsu', 'IMSU')], max_length=20),
        ),
    ]
