# Generated by Django 5.2 on 2026-07-22 06:11

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_campus_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='completion_proof_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_code',
            field=models.CharField(default=delivery.models.generate_delivery_code, max_length=6),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='pickup_proof_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
