# Generated by Django 5.2 on 2026-07-22 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryassignment_completion_proof_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='code_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='responsibility',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('studex_delivery', 'StudEx Delivery')], default='vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='responsibility_transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pickup', 'Pickup Verification'), ('completion', 'Completion Verification')], max_length=20)),
                ('evidence_image', models.URLField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to='delivery.deliveryassignment')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_verification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Verification Event',
                'verbose_name_plural': 'Delivery Verification Events',
                'ordering': ['occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'event_type'), name='one_event_per_assignment_per_type')],
            },
        ),
    ]
