# Generated by Django 5.2 on 2026-07-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryassignment_code_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('imsu', 'IMSU')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('delivery_time', models.TimeField()),
                ('cutoff_offset_minutes', models.PositiveIntegerField(default=15, help_text='Ordering closes this many minutes before delivery_time.')),
                ('max_orders', models.PositiveIntegerField()),
                ('days_of_week', models.JSONField(default=list, help_text='List of weekday ints (Monday=0 .. Sunday=6) this template applies to.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Template',
                'verbose_name_plural': 'Batch Templates',
                'ordering': ['vendor_id', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('imsu', 'IMSU')], max_length=20)),
                ('batch_date', models.DateField()),
                ('display_name', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('cutoff_time', models.DateTimeField()),
                ('max_orders', models.PositiveIntegerField()),
                ('current_orders', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, help_text='Which template generated this batch, if any — traces provenance only; editing this row never edits the template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_batches', to='delivery.batchtemplate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Batch',
                'verbose_name_plural': 'Delivery Batches',
                'ordering': ['-batch_date', 'delivery_time'],
                'unique_together': {('vendor', 'template', 'batch_date')},
            },
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='delivery.deliverybatch'),
        ),
    ]
