# Generated by Django 5.2 on 2026-07-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned to Rider'), ('picked_up', 'Picked Up from Vendor'), ('at_pickup_point', 'At Pickup Point'), ('completed', 'Collected by Buyer'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
    ]
