# Generated by Django 5.2 on 2026-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_deliveryassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryverificationevent',
            name='evidence_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
