# Generated by Django 5.2 on 2026-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_listing_campus'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listing',
            new_name='services_li_campus_74c2dc_idx',
            old_name='services_li_campus_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='services_li_campus_9f8cf0_idx',
            old_name='services_li_campus_avail_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='campus',
            field=models.CharField(choices=[('pau', 'PAU'), ('futo', 'FUTO'), ('all', 'All Campuses')], default='pau', max_length=20),
        ),
    ]
