# Generated by Django 5.2 on 2026-05-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_vendorofthemonth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='services_li_created_5c0553_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['campus', '-created_at'], name='services_li_campus_8ea6b1_idx'),
        ),
    ]
