# Generated by Django 5.2 on 2026-06-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_category_campus_booleans'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Brand New'), ('fairly_used', 'Fairly Used'), ('refurbished', 'Refurbished')], default='', help_text='Condition of the item (mainly for physical products)', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_time',
            field=models.CharField(blank=True, default='', help_text="Estimated delivery or completion time, e.g. '15-20 mins', '1-2 days'", max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, default='', help_text="Comma-separated keywords, e.g. 'Authentic, Handmade, Express'", max_length=300),
        ),
    ]
