# Generated by Django 5.2 on 2026-07-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_add_listing_brand_condition_delivery_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
