# Generated by Django 5.2 on 2026-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_seed_subcategories_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_per_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
