# Generated by Django 5.2 on 2026-07-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_searchquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('min_selections', models.PositiveIntegerField(default=0)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Add-on Group',
                'verbose_name_plural': 'Add-on Groups',
                'ordering': ['menu_item_id', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='services.addongroup')),
            ],
            options={
                'verbose_name': 'Add-on',
                'verbose_name_plural': 'Add-ons',
                'ordering': ['group_id', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['vendor_id', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('allergens', models.JSONField(blank=True, default=list, help_text='List of allergen names, e.g. ["peanuts", "dairy"].')),
                ('ingredients', models.TextField(blank=True, default='')),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden from buyer browsing without deactivating the underlying listing (e.g. a combo only orderable via a promo link).')),
                ('is_archived', models.BooleanField(default=False, help_text='Retired from the active menu but kept for historical order references (OrderItem.listing is PROTECTed).')),
                ('availability_window_start', models.TimeField(blank=True, null=True)),
                ('availability_window_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='services.listing')),
                ('menu_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='services.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.AddField(
            model_name='addongroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='services.menuitem'),
        ),
    ]
