# Generated by Django 5.2 on 2026-07-26 08:08

import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_addongroup_addon_menucategory_menuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/', validators=[studex.validators.validate_image])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
